using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace Model
{
    public partial class Articles : IPermission
    {
        public Articles()
        {
            Comments = new HashSet<Comments>();
        }

        [HideColumnIfAutoGenerated()]
        public int Id { get; set; }
        public string ShortName { get; set; }
        //[HideColumnIfAutoGenerated()]
        public string Decription { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime LastChange { get; set; }
        [HideColumnIfAutoGenerated()]
        public int? AuthorId { get; set; }
        [HideColumnIfAutoGenerated()]
        public int? DocumentTypeId { get; set; }
        public int? SecurityLabel { get; set; }

        [JsonIgnore]
        [HideColumnIfAutoGenerated()]
        public virtual Authors Author { get; set; }

        [JsonIgnore]
        public string Document_Type => DocumentType?.Type ?? "undefined";

        [HideColumnIfAutoGenerated()]
        public virtual DocumentTypes DocumentType { get; set; }

        [JsonIgnore]
        [HideColumnIfAutoGenerated()]
        public virtual SecurityLabels SecurityLabelNavigation { get; set; }

        [JsonIgnore]
        [HideColumnIfAutoGenerated()]
        public virtual ICollection<Comments> Comments { get; set; }

    }
}
